### PR TITLE
RSS - support 'yandex:full-text' tag

### PR DESCRIPTION
**Pull request by k0st1x**
Some sites (in Russia and other 'Commonwealth of Independent States' countries) uses RSS feeds with custom tag 'yandex:full-text' instead of 'description'.
Please accept this pull request so I can update project in 'AppStudio'.

This problem previously appeared on the forum https://social.msdn.microsoft.com/Forums/en-US/56dd6f3d-d74c-4ab6-8186-abdbfd59e668/rss-feed-with-nonstandard-tags?forum=wpappstudio

### CODE REVIEW

**Comment by k0st1x** [comment]
@javitosanchez please guide me,
Can I count on the fact that in the near future, this update will be applied on the http://appstudio.windows.com site?
Or will have to recompile the source codes of appstudio-project to apply these changes?

**Comment by javitosanchez** [comment]
This change will be included in our next release very soon in [http://appstudio.windows.com](http://appstudio.windows.com). But if you cannot wait, you can point to our next Nuget package beta version that we'll release for tomorrow morning. I can notify you for the Nuget package.

Thanks for the pull request by the way :-)

**Comment by k0st1x** [comment]
> change will be included in our next release very soon
this is very positive news!

Also I am interesting in supporting WP8 platform.
Is this change will be applied to appstudio.windows.com for Windows8 projects?

**Comment by k0st1x** [comment]
Currently tested "Windows AppStudio Data Providers 1.4.0-beta3" nuget package on my "appstudio project" and its works for me.
Thank you very much!

**Pull request merged**
